services:
  bachelor-diploma-thesis-template:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    working_dir: /opt/code
    volumes:
      - .:/opt/code
    command: make all
